dist: xenial
language: generic
services:
  - docker
addons:
  apt:
    packages:
      - docker-ce

before_script:
  - |
    if [[ "$TRAVIS_BRANCH" = master && -z "$TRAVIS_PULL_REQUEST_BRANCH" ]]; then
      TAG_LATEST=1
    else
      TAG_LATEST=0
    fi
    export TAG_LATEST
  - >-
    echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

jobs:
  include:
    - stage: deploy
      name: ubuntu-init
      script:
        - images=(ubuntu-init-{14.04,16.04,18.04} ubuntu-init-python-{14.04,16.04,18.04} ubuntu-init-python3-18.04)
        - ./build.sh pull "${images[@]}"
        - ./build.sh build "${images[@]}"
        - ./build.sh push "${images[@]}"
    - stage: deploy
      name: squid
      script:
        - ./build.sh pull squid-ssl
        - ./build.sh build squid-ssl
        - ./build.sh push squid-ssl
    - stage: deploy
      name: 11.0.7-jre-slim-buster-datadog-agent
      script:
        - ./build.sh pull jdk11-datadog-agent
        - ./build.sh build jdk11-datadog-agent
        - ./build.sh push jdk11-datadog-agent
    - stage: deploy
      name: flink
      script:
        - ./build.sh pull flink
        - ./build.sh build flink
        - ./build.sh push flink
